### ISSUE TITLE
Nodebb 3.x Compatibility (3 BUGS persist - 07.06.2023)

### ISSUE THREAD

**Issue by DroidBV8** [Wieloswiat/nodebb-plugin-ws-dice#117]
Hello @oplik0 

How are you ?

Is there any intention to make the nodebb-plugin-ws-dice plugin v3.x compatible (harmony) ?

Thanks for your answer my friend

**Comment by oplik0** [comment]
Yes, as I'll be upgrading to 3.0 myself I'll be going through the plugins I use and updating them to support v3 if they don't - with my own plugins probably being the first priority.

The only changes affecting this plugin are the move to Bootstrap5 and SCSS.

As this should be fairly simple I'll try to do this plugin first when I get to it - hopefully I'll have time to start migrating soon :)

**Comment by oplik0** [comment]
Done - 3.0.2 works fine with v3.
I'll probably adjust the styles later though - there seems to be too much whitespace between icons...

**Comment by DroidBV8** [comment]
ohh yeah
Will test this ASAP. Test user lol ;)

**Comment by DroidBV8** [comment]
Test now !!

Works fine on topic. Very good ;)

Just cosmetic tweaks to do. 
For example the timeline icon (left) is not centered like the nodeBB system events and whitespace between icons like you says

![image](https://user-images.githubusercontent.com/71468154/235518321-24c2e248-a1eb-45b0-8887-928c8da31159.png)

If you have time for the shoutbox plugin (working on V3) tell me but it's already amazing !

**Comment by oplik0** [comment]
Should be better now.

And I probably won't have time to make larger changes here unfortunately

**Comment by DroidBV8** [comment]
hello @oplik0 

I repair 2 bugs :

1- Seems to we can not see the result of several roll (just one) **without a refresh**. After refresh, the second result appear, 

2- and we can see that a system CSS element is moved (the gray dot on screenshot)

![image](https://user-images.githubusercontent.com/71468154/236047783-f8c6f09e-d21d-473e-9f27-b024026d40a0.png)

![image](https://user-images.githubusercontent.com/71468154/236048482-a310305b-73c9-48a1-a3c5-64687f2a20af.png)

--> Video to realize :

![test3](https://user-images.githubusercontent.com/71468154/236050239-fad09317-4773-48fa-b3a1-d88597be9c81.gif)

**Comment by DroidBV8** [comment]
Hello @oplik0 

In addition to the 2 other bugs mentioned in the post just above, I found another one just as annoying.

When we create an answer (not a roll of the dice) in any forum topic, we have this added to the timeline : 

![JW2wDArRSC](https://github.com/Wieloswiat/nodebb-plugin-ws-dice/assets/71468154/aaf160e0-6b5f-44cf-8096-f6c676ae17b6)

You have to refresh the page to see it disappear.

Thanks my friend

**Comment by DroidBV8** [comment]
Hello @opli

Any news about the fix for these 3 bugs ?

**Comment by oplik0** [comment]
Sorry, I'm a student on a very project-heavy course and the semester is coming to an end, so I'll unfortunately still be quite busy for the next few days.
In a week final exams will start, but I'll ironically have more free time then :)

**Comment by DroidBV8** [comment]
Hello @opli

Any news about the fix for these bugs my friends ?
For information, since v3.3. /roll not working on chat (connection lost)

cya

**Comment by oplik0** [comment]
3.0.4 should've fixed these now (both the chat not working and weird post event behavior)

**Comment by DroidBV8** [comment]
Test this release ASAP @oplik0 and tell you

Thanks

**Comment by oplik0** [comment]
@DroidBV8 seems that when I was removing some debug logging I reverted part of the fix for chat not working... 3.0.5 actually should work in chat (the other problems are resolved)

**Comment by DroidBV8** [comment]
Hello @oplik0 , 

Work great now. 

But new bug now : when the plugin is activate, there is bug display on public chat notification menu :

![image](https://github.com/Wieloswiat/nodebb-plugin-ws-dice/assets/71468154/b32e1b3d-13cb-4231-82c8-b8050e383b7f)

No problem when I deactivate the dice plugin

**Comment by oplik0** [comment]
@DroidBV8 Should be fixed in 3.0.7 I think
