### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by OldManUmby** [Wieloswiat/nodebb-plugin-ws-dice#93]
I just created a fresh NodeBB installation with no other plugins and no changes to any settings. I installed the Dice Roller Plugin, then "Rebuilt/Restarted". I then activated the plugin. Re-ordered and moved the plugin to 2nd place (just to me sure), then "Rebuilt/Restarted" again.

Tried several dice rolls. The "roll" is not rendered; nothing happens, just a post with the notation.

Suggestions? ... did I forget/miss something?

**Comment by DroidBV8** [comment]
Hello, 

Very strange, Ihave the 2.5.0 installed and it works very well.
BTW, what version of nodeBB you have... 

Have you a screenshot of the result ?

**Comment by OldManUmby** [comment]
NodeBB 2.5.7 ... going to reinstall from scratch to ensure all is well. I'll let you know in a few.

**Comment by OldManUmby** [comment]
Sorry, very busy. So, I reinstalled everything from scratch as follows ...

1. Installed NodeBB v2.5.8 ... no issues; everything working fine.
2. I installed nothing else.
3. Dice Roller: Plugins > Install Plugins > Search "Dice".
4. Click "Install" (Green Button) ... no issues.
5. Enable the dice plugin.
6. Dashboard > "Rebuild & Restart" (Red Button).
7. Test Dice Roller in Post ... "/roll 1d20" ... no results (see attached screenshot).

Am I missing something obvious?

![Screenshot 2022-11-16 at 8 24 25 PM](https://user-images.githubusercontent.com/22547499/202348270-e4d23ac9-7527-4c2a-8ca1-df5537aa951f.jpg)

**Comment by OldManUmby** [comment]
Any ideas?

**Comment by oplik0** [comment]
This is an issue just with with NodeBB v2.5.8 and will be fixed in the next v2 release, for now you can edit your `package.json` to set `nodebb-theme-persona` to version `12.1.12` and run `npm install`

**Comment by OldManUmby** [comment]
I guess I'll have to wait. "npm install nodebb-theme-persona@12.1.12" isn't an option for me; I get an error; I'm using Cloudron.

THX for the "Investigation"! ... I travel for a living, hope this gets works soon; I need a fix :)

**Comment by OldManUmby** [comment]
If you're confident we'll get this working, then I will continue developing the site? ... as I have lots of content to put up. THX!

**Comment by oplik0** [comment]
I was testing here, so you can see it working on NodeBB 2.5.8 with just that one dependency updated: https://nodebb-demo.opliko.dev/topic/1/welcome-to-your-nodebb

**Comment by OldManUmby** [comment]
I managed to get Persona 12.1.12 installed, the dice roller seems to be working now. Thanks for the help!

**Comment by OldManUmby** [comment]
FYI ... NodeBB v2.6.0 installed Persona 12.1.12 automatically. The dice roller still works fine. THX!
